### ISSUE TITLE
The app doesn't work with new versions of OSx

### ISSUE THREAD

**Issue by vpascual** [tmcw/minute-agent#22]
Is there a way to make it work again?

**Comment by sheriferson** [comment]
It works for me on the latest version of OS X (10.11.4).

Sometimes OS X's privacy and accessibility permissions break after an update. I recall that minute-agent did stop working after the latest point release. Try going to System Preferences > Security & Privacy > Accessibility, remove "hihowareyou" from the list, and add it again manually and make sure it's checked. Even if it looks like it's there and checked, try removing it and adding it again, and then reboot.

**Comment by vpascual** [comment]
You're totally right! I've lost two years of keystrokes for not checking the data! Shame on me!
Thanks for the help, it works like a charm again!

**Comment by tmcw** [comment]
Sorry about that, I'll add a note to the readme with a reminder. Also would happily accept a PR implementing a reminder.
